// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_WaterParkStart.h"
#include "ui_GraphResults.h"
#include "ui_SwingStart.h"
#include "ui_FileSelection.h"
#include "ui_FerisWheel.h"
#include "ui_BlackMamba.h"
#include "ui_SudoMode.h"
#include "ui_SplashScreen.h"
#include "ui_HoistSystem.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_statistics_png);   // assets/statistics.png
LV_IMG_DECLARE( ui_img_amitlogo_png);   // assets/amitlogo.png
LV_IMG_DECLARE( ui_img_1504419431);   // assets/theme-park.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
