// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onBackButton(lv_event_t * e);
void onStartButton(lv_event_t * e);
void connectBT(lv_event_t * e);
void validateSudoCode(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
