// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_FILESELECTION_H
#define UI_FILESELECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FileSelection
extern void ui_FileSelection_screen_init(void);
extern void ui_FileSelection_screen_destroy(void);
extern lv_obj_t *ui_FileSelection;
extern void ui_event_logo3( lv_event_t * e);
extern lv_obj_t *ui_logo3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_FileSelector;
extern lv_obj_t *ui_ButtonZone;
extern void ui_event_Run( lv_event_t * e);
extern lv_obj_t *ui_Run;
extern lv_obj_t *ui_StartStopLabel3;
extern void ui_event_StartStop5( lv_event_t * e);
extern lv_obj_t *ui_StartStop5;
extern lv_obj_t *ui_StartStopLabel5;
extern lv_obj_t *ui_ConnectedLabel;
extern lv_obj_t *ui_SSID;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

