// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_FERISWHEEL_H
#define UI_FERISWHEEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FerisWheel
extern void ui_FerisWheel_screen_init(void);
extern void ui_FerisWheel_screen_destroy(void);
extern lv_obj_t *ui_FerisWheel;
extern lv_obj_t *ui_Speed3;
extern void ui_event_SpeedControl3( lv_event_t * e);
extern lv_obj_t *ui_SpeedControl3;
extern void ui_event_StartStop4( lv_event_t * e);
extern lv_obj_t *ui_StartStop4;
extern lv_obj_t *ui_StartStopLabel4;
extern lv_obj_t *ui_SensorAFrame3;
extern lv_obj_t *ui_SensorAValue3;
extern lv_obj_t *ui_SensorBFrame2;
extern lv_obj_t *ui_SensorBValue2;
extern lv_obj_t *ui_DataResult1;
extern void ui_event_Image3( lv_event_t * e);
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_logo4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

