// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_FerisWheel = NULL;lv_obj_t *ui_Speed3 = NULL;lv_obj_t *ui_SpeedControl3 = NULL;lv_obj_t *ui_StartStop4 = NULL;lv_obj_t *ui_StartStopLabel4 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_logo4 = NULL;lv_obj_t *ui_Container6 = NULL;lv_obj_t *ui_SensorAFrame3 = NULL;lv_obj_t *ui_SensorAValue3 = NULL;lv_obj_t *ui_Label18 = NULL;lv_obj_t *ui_Container7 = NULL;lv_obj_t *ui_SensorBFrame2 = NULL;lv_obj_t *ui_SensorBValue2 = NULL;lv_obj_t *ui_Label19 = NULL;
// event funtions
void ui_event_SpeedControl3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Speed3, target, "", "%");
}
}

void ui_event_StartStop4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_StartStop4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_checked_set_text_value( ui_StartStopLabel4, target, "Stop", "Start");
      _ui_state_modify( ui_SpeedControl3, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
      onStartButton( e );
}
}

void ui_event_Image3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_GraphResults, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_GraphResults_screen_init);
}
}

void ui_event_logo4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SudoMode, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SudoMode_screen_init);
}
}

// build funtions

void ui_FerisWheel_screen_init(void)
{
ui_FerisWheel = lv_obj_create(NULL);
lv_obj_remove_flag( ui_FerisWheel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Speed3 = lv_label_create(ui_FerisWheel);
lv_obj_set_width( ui_Speed3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Speed3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Speed3, 1 );
lv_obj_set_y( ui_Speed3, 107 );
lv_obj_set_align( ui_Speed3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Speed3,"0%");

ui_SpeedControl3 = lv_arc_create(ui_FerisWheel);
lv_obj_set_width( ui_SpeedControl3, 200);
lv_obj_set_height( ui_SpeedControl3, 200);
lv_obj_set_x( ui_SpeedControl3, 0 );
lv_obj_set_y( ui_SpeedControl3, 20 );
lv_obj_set_align( ui_SpeedControl3, LV_ALIGN_CENTER );
lv_obj_add_state( ui_SpeedControl3, LV_STATE_CHECKED );     /// States
lv_obj_add_flag( ui_SpeedControl3, LV_OBJ_FLAG_FLOATING );   /// Flags
lv_arc_set_value(ui_SpeedControl3, 0);
lv_obj_set_style_bg_color(ui_SpeedControl3, lv_color_hex(0xF3F3F3), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_SpeedControl3, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_arc_color(ui_SpeedControl3, lv_color_hex(0xE7E7E7), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_arc_opa(ui_SpeedControl3, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_set_style_bg_color(ui_SpeedControl3, lv_color_hex(0x5D5B5B), LV_PART_KNOB | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_SpeedControl3, 255, LV_PART_KNOB| LV_STATE_DISABLED);

ui_StartStop4 = lv_button_create(ui_FerisWheel);
lv_obj_set_width( ui_StartStop4, 150);
lv_obj_set_height( ui_StartStop4, 150);
lv_obj_set_y( ui_StartStop4, 20 );
lv_obj_set_x( ui_StartStop4, lv_pct(0) );
lv_obj_set_align( ui_StartStop4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_StartStop4, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_StartStop4, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StartStop4, 10000000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartStop4, lv_color_hex(0x54B034), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartStop4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartStop4, lv_color_hex(0xBA4646), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_StartStop4, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_StartStopLabel4 = lv_label_create(ui_StartStop4);
lv_obj_set_width( ui_StartStopLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartStopLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_StartStopLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartStopLabel4,"Start");

ui_Image3 = lv_image_create(ui_FerisWheel);
lv_image_set_src(ui_Image3, &ui_img_statistics_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image3, -8 );
lv_obj_set_y( ui_Image3, -8 );
lv_obj_set_align( ui_Image3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_Image3, 10);
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_logo4 = lv_image_create(ui_FerisWheel);
lv_image_set_src(ui_logo4, &ui_img_amitlogo_png);
lv_obj_set_width( ui_logo4, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_logo4, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_logo4, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_logo4, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_logo4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_FerisWheel);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 87);
lv_obj_set_height( ui_Container6, 55);
lv_obj_set_x( ui_Container6, 7 );
lv_obj_set_y( ui_Container6, 7 );
lv_obj_remove_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SensorAFrame3 = lv_obj_create(ui_Container6);
lv_obj_set_width( ui_SensorAFrame3, 87);
lv_obj_set_height( ui_SensorAFrame3, 32);
lv_obj_set_align( ui_SensorAFrame3, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_SensorAFrame3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SensorAFrame3, lv_color_hex(0xFFF58A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensorAFrame3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorAValue3 = lv_label_create(ui_SensorAFrame3);
lv_obj_set_width( ui_SensorAValue3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorAValue3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SensorAValue3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorAValue3,"45°");

ui_Label18 = lv_label_create(ui_Container6);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label18,"Angle");
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_FerisWheel);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 87);
lv_obj_set_height( ui_Container7, 55);
lv_obj_set_x( ui_Container7, -7 );
lv_obj_set_y( ui_Container7, 7 );
lv_obj_set_align( ui_Container7, LV_ALIGN_TOP_RIGHT );
lv_obj_remove_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SensorBFrame2 = lv_obj_create(ui_Container7);
lv_obj_set_width( ui_SensorBFrame2, 87);
lv_obj_set_height( ui_SensorBFrame2, 32);
lv_obj_set_align( ui_SensorBFrame2, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_SensorBFrame2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SensorBFrame2, lv_color_hex(0xB3BFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensorBFrame2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorBValue2 = lv_label_create(ui_SensorBFrame2);
lv_obj_set_width( ui_SensorBValue2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorBValue2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SensorBValue2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorBValue2,"5 spins");

ui_Label19 = lv_label_create(ui_Container7);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label19,"Rot");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SpeedControl3, ui_event_SpeedControl3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StartStop4, ui_event_StartStop4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_logo4, ui_event_logo4, LV_EVENT_ALL, NULL);

}

void ui_FerisWheel_screen_destroy(void)
{
   if (ui_FerisWheel) lv_obj_del(ui_FerisWheel);

// NULL screen variables
ui_FerisWheel= NULL;
ui_Speed3= NULL;
ui_SpeedControl3= NULL;
ui_StartStop4= NULL;
ui_StartStopLabel4= NULL;
ui_Image3= NULL;
ui_logo4= NULL;
ui_Container6= NULL;
ui_SensorAFrame3= NULL;
ui_SensorAValue3= NULL;
ui_Label18= NULL;
ui_Container7= NULL;
ui_SensorBFrame2= NULL;
ui_SensorBValue2= NULL;
ui_Label19= NULL;

}
