// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_GraphResults = NULL;lv_obj_t *ui_Image8 = NULL;lv_obj_t *ui_Chart1 = NULL;lv_obj_t *ui_Chart1_Xaxis = NULL;lv_obj_t *ui_Chart1_Yaxis1 = NULL;lv_obj_t *ui_Chart1_Yaxis2 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Image9 = NULL;
// event funtions
void ui_event_Image9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onBackButton( e );
}
}

// build funtions

void ui_GraphResults_screen_init(void)
{
ui_GraphResults = lv_obj_create(NULL);
lv_obj_remove_flag( ui_GraphResults, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_image_create(ui_GraphResults);
lv_image_set_src(ui_Image8, &ui_img_amitlogo_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Image8, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart1 = lv_chart_create(ui_GraphResults);
lv_obj_set_width( ui_Chart1, 200);
lv_obj_set_height( ui_Chart1, 100);
lv_obj_set_x( ui_Chart1, 5 );
lv_obj_set_y( ui_Chart1, -3 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart1, 14);

ui_Chart1_Xaxis = lv_scale_create( ui_Chart1 );
lv_scale_set_mode( ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Chart1_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Chart1_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart1_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Chart1_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart1_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Chart1_Xaxis, 5, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Chart1_Xaxis, 0, 13 > 0 ? 13 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Chart1_Xaxis, (13>0 ? 13-1 : 0) * 1 + 1 );
lv_scale_set_major_tick_every( ui_Chart1_Xaxis, 1 >= 1 ? 1 : 1 );
ui_Chart1_Yaxis1 = lv_scale_create( ui_Chart1 );
lv_scale_set_mode( ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Chart1_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Chart1_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart1_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart1_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart1_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart1_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_Chart1_Yaxis2 = lv_scale_create( ui_Chart1 );
lv_scale_set_mode( ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Chart1_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Chart1_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart1_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart1_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart1_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart1_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFFF58A), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 2,3,4,5,20,40,6 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
lv_chart_series_t* ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFFBBE1), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_2_array[] = { 2,3,4,5,20,40,60,30,60,8,20,40 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
lv_chart_series_t* ui_Chart1_series_3 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xB3BFFF), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_Chart1_series_3_array[] = { 0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_3, ui_Chart1_series_3_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Chart1, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Label5 = lv_label_create(ui_GraphResults);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 0 );
lv_obj_set_y( ui_Label5, -87 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Results graph");

ui_Image9 = lv_image_create(ui_GraphResults);
lv_image_set_src(ui_Image9, &ui_img_1504419431);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image9, -9 );
lv_obj_set_y( ui_Image9, -8 );
lv_obj_set_align( ui_Image9, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_Image9, 15);
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Image9, ui_event_Image9, LV_EVENT_ALL, NULL);

}

void ui_GraphResults_screen_destroy(void)
{
   if (ui_GraphResults) lv_obj_del(ui_GraphResults);

// NULL screen variables
ui_GraphResults= NULL;
ui_Image8= NULL;
ui_Chart1= NULL;
ui_Label5= NULL;
ui_Image9= NULL;

}
