// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_GRAPHRESULTS_H
#define UI_GRAPHRESULTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GraphResults
extern void ui_GraphResults_screen_init(void);
extern void ui_GraphResults_screen_destroy(void);
extern lv_obj_t *ui_GraphResults;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Chart1_Xaxis;
extern lv_obj_t *ui_Chart1_Yaxis1;
extern lv_obj_t *ui_Chart1_Yaxis2;
extern lv_obj_t *ui_Label5;
extern void ui_event_Image9( lv_event_t * e);
extern lv_obj_t *ui_Image9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

