// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Chart2 = NULL;lv_obj_t *ui_Chart2_Xaxis = NULL;lv_obj_t *ui_Chart2_Yaxis1 = NULL;lv_obj_t *ui_Chart2_Yaxis2 = NULL;lv_obj_t *ui_Slider1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Chart2 = lv_chart_create(ui_Screen1);
lv_obj_set_width( ui_Chart2, 230);
lv_obj_set_height( ui_Chart2, 190);
lv_obj_set_x( ui_Chart2, 0 );
lv_obj_set_y( ui_Chart2, -8 );
lv_obj_set_align( ui_Chart2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Chart2, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart2, 4);

ui_Chart2_Xaxis = lv_scale_create( ui_Chart2 );
lv_scale_set_mode( ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Chart2_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Chart2_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart2_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Chart2_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart2_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Chart2_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Chart2_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Chart2_Xaxis, (5>0 ? 5-1 : 0) * 1 + 1 );
lv_scale_set_major_tick_every( ui_Chart2_Xaxis, 1 >= 1 ? 1 : 1 );
ui_Chart2_Yaxis1 = lv_scale_create( ui_Chart2 );
lv_scale_set_mode( ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Chart2_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Chart2_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart2_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart2_Yaxis1, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart2_Yaxis1, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart2_Yaxis1, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_Chart2_Yaxis1, 0 >= 1 ? 0 : 1 );
ui_Chart2_Yaxis2 = lv_scale_create( ui_Chart2 );
lv_scale_set_mode( ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Chart2_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Chart2_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart2_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart2_Yaxis2, 0, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart2_Yaxis2, 0, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart2_Yaxis2, (0 > 0 ? 0-1 : 0) * 0 + 1 );
lv_scale_set_major_tick_every( ui_Chart2_Yaxis2, 0 >= 1 ? 0 : 1 );
lv_scale_set_label_show( ui_Chart2_Yaxis2, false );
lv_chart_series_t* ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart2_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Chart2, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Slider1 = lv_slider_create(ui_Screen1);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 150);
lv_obj_set_height( ui_Slider1, 10);
lv_obj_set_x( ui_Slider1, 60 );
lv_obj_set_y( ui_Slider1, -178 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_transform_rotation(ui_Slider1, 900, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Slider1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Slider1, lv_obj_get_style_pad_right(ui_Slider1,LV_PART_MAIN) + 1, LV_PART_MAIN );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Chart2= NULL;
ui_Slider1= NULL;

}
