// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SWINGSTART_H
#define UI_SWINGSTART_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SwingStart
extern void ui_SwingStart_screen_init(void);
extern void ui_SwingStart_screen_destroy(void);
extern lv_obj_t *ui_SwingStart;
extern lv_obj_t *ui_Speed1;
extern void ui_event_SpeedControl1( lv_event_t * e);
extern lv_obj_t *ui_SpeedControl1;
extern void ui_event_StartStop1( lv_event_t * e);
extern lv_obj_t *ui_StartStop1;
extern lv_obj_t *ui_StartStopLabel1;
extern lv_obj_t *ui_SensorAFrame1;
extern lv_obj_t *ui_SensorAValue1;
extern lv_obj_t *ui_SensorBFrame1;
extern lv_obj_t *ui_SensorBValue1;
extern lv_obj_t *ui_DataResult;
extern void ui_event_Image1( lv_event_t * e);
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_logo1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

