// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SUDOMODE_H
#define UI_SUDOMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SudoMode
extern void ui_SudoMode_screen_init(void);
extern void ui_SudoMode_screen_destroy(void);
extern lv_obj_t *ui_SudoMode;
extern void ui_event_logo5( lv_event_t * e);
extern lv_obj_t *ui_logo5;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Code;
extern void ui_event_Keyboard1( lv_event_t * e);
extern lv_obj_t *ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

