// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_SudoMode = NULL;lv_obj_t *ui_logo5 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Code = NULL;lv_obj_t *ui_Keyboard1 = NULL;
// event funtions
void ui_event_logo5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      onBackButton( e );
}
}

void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      validateSudoCode( e );
}
}

// build funtions

void ui_SudoMode_screen_init(void)
{
ui_SudoMode = lv_obj_create(NULL);
lv_obj_remove_flag( ui_SudoMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_logo5 = lv_image_create(ui_SudoMode);
lv_image_set_src(ui_logo5, &ui_img_amitlogo_png);
lv_obj_set_width( ui_logo5, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_logo5, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_logo5, 267 );
lv_obj_set_y( ui_logo5, -187 );
lv_obj_set_align( ui_logo5, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_logo5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_logo5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_SudoMode);
lv_obj_set_width( ui_Label2, 310);
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 7 );
lv_obj_set_y( ui_Label2, 8 );
lv_label_set_text(ui_Label2,"SUDO MODE");
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Code = lv_textarea_create(ui_SudoMode);
lv_obj_set_width( ui_Code, 164);
lv_obj_set_height( ui_Code, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_Code, 0 );
lv_obj_set_y( ui_Code, -63 );
lv_obj_set_align( ui_Code, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Code,6);
lv_textarea_set_placeholder_text(ui_Code,"Enter Code");
lv_textarea_set_one_line(ui_Code,true);
lv_textarea_set_password_mode(ui_Code, true);
lv_obj_set_style_text_align(ui_Code, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_Code, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_Keyboard1 = lv_keyboard_create(ui_SudoMode);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 235);
lv_obj_set_height( ui_Keyboard1, 121);
lv_obj_set_x( ui_Keyboard1, 0 );
lv_obj_set_y( ui_Keyboard1, 29 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_logo5, ui_event_logo5, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard1,ui_Code);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);

}

void ui_SudoMode_screen_destroy(void)
{
   if (ui_SudoMode) lv_obj_del(ui_SudoMode);

// NULL screen variables
ui_SudoMode= NULL;
ui_logo5= NULL;
ui_Label2= NULL;
ui_Code= NULL;
ui_Keyboard1= NULL;

}
