// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_WATERPARKSTART_H
#define UI_WATERPARKSTART_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WaterParkStart
extern void ui_WaterParkStart_screen_init(void);
extern void ui_WaterParkStart_screen_destroy(void);
extern lv_obj_t *ui_WaterParkStart;
extern void ui_event_StartStop( lv_event_t * e);
extern lv_obj_t *ui_StartStop;
extern lv_obj_t *ui_StartStopLabel;
extern lv_obj_t *ui_SensorAFrame;
extern lv_obj_t *ui_SensorAValue;
extern lv_obj_t *ui_SensorBFrame;
extern lv_obj_t *ui_SensorBValue;
extern void ui_event_Image7( lv_event_t * e);
extern lv_obj_t *ui_Image7;
extern void ui_event_logo( lv_event_t * e);
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_SensorBFrame3;
extern lv_obj_t *ui_SensorCValue;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

