// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_WaterParkStart = NULL;lv_obj_t *ui_BContainer = NULL;lv_obj_t *ui_SensorBFrame3 = NULL;lv_obj_t *ui_SensorCValue = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_logo = NULL;lv_obj_t *ui_AContainer = NULL;lv_obj_t *ui_SensorBFrame4 = NULL;lv_obj_t *ui_SensorCValue1 = NULL;lv_obj_t *ui_ALabel = NULL;lv_obj_t *ui_WaterSlide_Label = NULL;
// event funtions
void ui_event_Image7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_GraphResults, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_GraphResults_screen_init);
}
}

void ui_event_logo( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_SudoMode, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_SudoMode_screen_init);
}
}

// build funtions

void ui_WaterParkStart_screen_init(void)
{
ui_WaterParkStart = lv_obj_create(NULL);
lv_obj_remove_flag( ui_WaterParkStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BContainer = lv_obj_create(ui_WaterParkStart);
lv_obj_remove_style_all(ui_BContainer);
lv_obj_set_width( ui_BContainer, 257);
lv_obj_set_height( ui_BContainer, 32);
lv_obj_set_x( ui_BContainer, 0 );
lv_obj_set_y( ui_BContainer, 6 );
lv_obj_set_align( ui_BContainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_BContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SensorBFrame3 = lv_obj_create(ui_BContainer);
lv_obj_set_width( ui_SensorBFrame3, 177);
lv_obj_set_height( ui_SensorBFrame3, 32);
lv_obj_set_align( ui_SensorBFrame3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_SensorBFrame3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SensorBFrame3, lv_color_hex(0xB3BFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensorBFrame3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorCValue = lv_label_create(ui_SensorBFrame3);
lv_obj_set_width( ui_SensorCValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorCValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SensorCValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorCValue,"0ms");

ui_Label1 = lv_label_create(ui_BContainer);
lv_obj_set_width( ui_Label1, 18);
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -99 );
lv_obj_set_y( ui_Label1, 0 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"B");
lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_image_create(ui_WaterParkStart);
lv_image_set_src(ui_Image7, &ui_img_statistics_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Image7, -8 );
lv_obj_set_y( ui_Image7, -8 );
lv_obj_set_align( ui_Image7, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_ext_click_area(ui_Image7, 10);
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_logo = lv_image_create(ui_WaterParkStart);
lv_image_set_src(ui_logo, &ui_img_amitlogo_png);
lv_obj_set_width( ui_logo, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_logo, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_logo, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_logo, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AContainer = lv_obj_create(ui_WaterParkStart);
lv_obj_remove_style_all(ui_AContainer);
lv_obj_set_width( ui_AContainer, 257);
lv_obj_set_height( ui_AContainer, 32);
lv_obj_set_x( ui_AContainer, 0 );
lv_obj_set_y( ui_AContainer, -34 );
lv_obj_set_align( ui_AContainer, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_AContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SensorBFrame4 = lv_obj_create(ui_AContainer);
lv_obj_set_width( ui_SensorBFrame4, 177);
lv_obj_set_height( ui_SensorBFrame4, 32);
lv_obj_set_align( ui_SensorBFrame4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_SensorBFrame4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SensorBFrame4, lv_color_hex(0xFFF58A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SensorBFrame4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorCValue1 = lv_label_create(ui_SensorBFrame4);
lv_obj_set_width( ui_SensorCValue1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorCValue1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SensorCValue1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorCValue1,"0ms");

ui_ALabel = lv_label_create(ui_AContainer);
lv_obj_set_width( ui_ALabel, 18);
lv_obj_set_height( ui_ALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ALabel, -99 );
lv_obj_set_y( ui_ALabel, 0 );
lv_obj_set_align( ui_ALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ALabel,"A");
lv_obj_set_style_text_align(ui_ALabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ALabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WaterSlide_Label = lv_label_create(ui_WaterParkStart);
lv_obj_set_width( ui_WaterSlide_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WaterSlide_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WaterSlide_Label, 0 );
lv_obj_set_y( ui_WaterSlide_Label, -100 );
lv_obj_set_align( ui_WaterSlide_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_WaterSlide_Label,"Water Slide");
lv_obj_add_flag( ui_WaterSlide_Label, LV_OBJ_FLAG_EVENT_BUBBLE );   /// Flags
lv_obj_set_style_text_font(ui_WaterSlide_Label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_logo, ui_event_logo, LV_EVENT_ALL, NULL);

}

void ui_WaterParkStart_screen_destroy(void)
{
   if (ui_WaterParkStart) lv_obj_del(ui_WaterParkStart);

// NULL screen variables
ui_WaterParkStart= NULL;
ui_BContainer= NULL;
ui_SensorBFrame3= NULL;
ui_SensorCValue= NULL;
ui_Label1= NULL;
ui_Image7= NULL;
ui_logo= NULL;
ui_AContainer= NULL;
ui_SensorBFrame4= NULL;
ui_SensorCValue1= NULL;
ui_ALabel= NULL;
ui_WaterSlide_Label= NULL;

}
